name: student_tracker
version: 1.0.0+1
publish_to: none
description: An application which permits parents to track the progress of their kids in school
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.63.0
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  image_picker: ^0.8.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#D3D3D3"
    theme_color: "#4169E1"
