// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ12gYO55S-ZeUYisQYQ8UJA_Y56visMw',
    appId: '1:47659406314:web:038b931cbea3bf70f75893',
    messagingSenderId: '47659406314',
    projectId: 'student-tracker-36278',
    authDomain: 'student-tracker-36278.firebaseapp.com',
    storageBucket: 'student-tracker-36278.appspot.com',
    measurementId: 'G-3S0F2CYCPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrDiYt64_Gf30MzEGCrT2QeawLF5pwLc',
    appId: '1:47659406314:android:efc1c24f255ac704f75893',
    messagingSenderId: '47659406314',
    projectId: 'student-tracker-36278',
    storageBucket: 'student-tracker-36278.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAluRJeceXa72flmm7_j0dR2HQoboC56L0',
    appId: '1:47659406314:ios:87a7b47a8d4d91d7f75893',
    messagingSenderId: '47659406314',
    projectId: 'student-tracker-36278',
    storageBucket: 'student-tracker-36278.appspot.com',
    iosClientId: '47659406314-0ltrvi005nae12vrg08ct41otvltgvfe.apps.googleusercontent.com',
    iosBundleId: 'com.Micheduc25.studenttracker.studentTracker',
  );
}
